### ISSUE TITLE
Stream UDP to multiple wled strips

### ISSUE THREAD

**Issue by ghost** [Lord-FEAR/Prismatik-WLED-WiFi#6]
Is there a way to put multiple ip addresses in the config so that I can have 2 strips synced to prismatic

**Comment by Lord-FEAR** [comment]
Use the broadcast address x.x.x.255 (for example, 192.168.0.255 if your devices are on the 192.168.0.X network) in which case all devices on the network will be synchronized. To do this, all devices must work on the same port (default 21324)

UDP_IP_ADDRESS - Exact ip or x.x.x.255 for broadband (convenient with dynamic ip on the device)
UDP_PORT_NO - Port on the WLED device (default 21324) Settings -> Sync Interfaces -> UDP Port

**Comment by ghost** [comment]
Thank you that works! I did notice that although the refreshrate never changed (30fps) the delay between the strips and the display are much longer and the strip will hang for a few seconds on a frame then go to another rather than a smooth stream of pixels. I have noticed all of these changed after changing the ip address, is there any way to alleviate some of these issues? thank you so much!

**Comment by Lord-FEAR** [comment]
I have not encountered such a problem. What version of WLED are you using? There were problems when using a bad router and the Wi-Fi band is very busy. I had to abandon Prismatik because it runs slowly and even 60 frames per second give a visible delay using a monitor at 144 Hz. With a 60 Hz monitor it looks good

If you use Discord, you can ask questions there. https://discord.gg/2F2X9VA
